apiVersion: v1
kind: Pod
metadata:
  name: alcove
spec:
  containers:
    - name: alcove
      image: us.gcr.io/alcove-1235/hdf5-works
      command: ['jupyter', 'notebook', '--no-browser', '--ip=0.0.0.0', '--port=8888']
      imagePullPolicy: Always
      ports:
        - containerPort: 8888
          hostPort: 80
